version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: authorization_server_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  

